baseURL = "http://unto.re/"
languageCode = "en-us"
title = "untoreh's site"
theme = "nix"

[params]
  Name = "untoreh"
  HeaderUsername = "untoreh"
  HeaderHostname = "unto.re"
  About = "a very bad person :*"
  ProfilePicture = "https://s.gravatar.com/avatar/bff2be7f27669197007df27c2f58c7e1?s=80"
  # StackExchangeID = "your_stackexchange_id"
  # StackOverflowID = "your_stackoverflow_id"
  GithubID = "untoreh"
  GitlabId = "untoreh"
  TwitterID = "untoreh"
  # CodepenID = "your_codepen"
  # LinkedInID = "your_linkedin"
  # GoogleplusID = "your_googleplus"
  # FacebookID = "your_facebook"
  # InstagramID = "your_instagram"
  # TelegramID = "your_telegram"
  # RedditID = "your_reddit"
  # Email = "your_email"
  # Phone = "+1-201-555-0123"
  # Mobile = "+1-201-555-0123"
  # GoogleAnalytics = "your_google_analytics_id"
  # SlackURL = "https://join.slack.com/..."
  # PayPalMeID = "https://www.paypal.me/..."
  # XingURL = "https://www.xing.com/profile/..."
  # CvURL = "your_cv_url"
